# Test values with Bitnami MongoDB subchart enabled
mongodb:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi

persistence:
  enabled: true
  size: 1Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
