# Test values with PodDisruptionBudget enabled
replicaCount: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1

persistence:
  enabled: true
  size: 1Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi