# Test values with ServiceMonitor enabled
serviceMonitor:
  enabled: true
  interval: "60s"
  scrapeTimeout: "15s"
  labels:
    monitoring: prometheus

persistence:
  enabled: true
  size: 1Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
