{{- if and .Values.ingress.enabled (contains "gce" (.Values.ingress.className | lower)) }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: unifi-backend-config
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  healthCheck:
    checkIntervalSec: 10
    port: 8443
    type: HTTPS
    requestPath: /status
  protocols:
    - HTTPS
  securityPolicy:
    name: "cloud-armor-policy"
{{- end }}
