{{- if .Values.mongodbCommunity.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unifi.fullname" . }}-mongodb-password
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ randAlphaNum 16 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unifi.fullname" . }}-mongodb-database
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "unifi.fullname" . }}-mongodb-database
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "unifi.fullname" . }}-mongodb-database
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "unifi.fullname" . }}-mongodb-database
roleRef:
  kind: Role
  name: {{ include "unifi.fullname" . }}-mongodb-database
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ include "unifi.fullname" . }}-mongodb
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  members: 1
  type: ReplicaSet
  version: {{ .Values.mongodbCommunity.version | quote }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    {{- range .Values.mongodbCommunity.users }}
    - name: {{ .name }}
      db: {{ .db }}
      passwordSecretRef:
        name: {{ .passwordSecretRef.name }}
      roles:
        {{- range .roles }}
        - name: {{ .name }}
          db: {{ .db }}
        {{- end }}
      scramCredentialsSecretName: {{ .scramCredentialsSecretName }}
    {{- end }}
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "unifi.fullname" . }}-mongodb-database
          containers:
            - name: mongod
              resources:
                {{- toYaml .Values.mongodbCommunity.resources | nindent 16 }}
      {{- if .Values.mongodbCommunity.persistence.enabled }}
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            {{- if .Values.mongodbCommunity.persistence.storageClass }}
            storageClassName: {{ .Values.mongodbCommunity.persistence.storageClass }}
            {{- end }}
            resources:
              requests:
                storage: {{ .Values.mongodbCommunity.persistence.size }}
      {{- end }}
{{- end }}
