apiVersion: v2
name: unifi
description: A Helm chart for UniFi Network Controller
type: application
version: 0.2.0
appVersion: 9.3.45
keywords:
  - unifi
  - networking
  - controller
  - ubiquiti
home: https://ui.com/
sources:
  - https://github.com/jacobalberty/unifi-docker
maintainers:
  - name: hannoeru
    email: me@hanlee.co
